### ISSUE TITLE
python-bingx 1.0.1 problem

### ISSUE THREAD

**Issue by RobinDala2020** [niewiemczego/python-bingx#12]
Dear niewiemczego
Please change the name of the primary folder from **binx** to **bingX**.
I faced with bellow error when I installed and used python-bingx 1.0.1

![bingX](https://github.com/niewiemczego/python-bingx/assets/129304303/3ca2c44f-21de-4cce-9f86-ec2fd9c5b5ec)

BR

**Comment by niewiemczego** [comment]
Please don't spam with the issues, right now I don't have any idea which one you have solved and with what issues u need help. I will close all issues if u need still help open new ticket with given issue and make sure to cominiate within this opened issue in comment section and not by creating another new issues
