### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by bryanplace86** [niewiemczego/python-bingx#4]
Hello,

I'm getting the following error when trying to import python-Bingx module. I've tried both python 3.8 and 3.9 so far and haven't had any luck. Any ideas?

Error:
Traceback (most recent call last):

  File ~\anaconda3\envs\asdf\lib\site-packages\IPython\core\interactiveshell.py:3505 in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  Cell In[1], line 1
    import bingX

  File ~\anaconda3\envs\asdf\lib\site-packages\bingX\__init__.py:2
    from bingX.main import BingX

  File ~\anaconda3\envs\asdf\lib\site-packages\bingX\main.py:2
    from bingX.perpetual.v2 import PerpetualV2

  File ~\anaconda3\envs\asdf\lib\site-packages\bingX\perpetual\v2\__init__.py:1
    from .perpetual import PerpetualV2

  File ~\anaconda3\envs\asdf\lib\site-packages\bingX\perpetual\v2\perpetual.py:1
    from bingX.perpetual.v2.account import Account

  File ~\anaconda3\envs\asdf\lib\site-packages\bingX\perpetual\v2\account.py:3
    from bingX._http_manager import _HTTPManager

  File ~\anaconda3\envs\asdf\lib\site-packages\bingX\_http_manager.py:56
    match method:
          ^
SyntaxError: invalid syntax

**Comment by bryanplace86** [comment]
This was resolved by installing Python 3.10

**Comment by niewiemczego** [comment]
Hey! The project uses match statement which was introduced in python 3.10, so you have to use at least 3.10 version
