### ISSUE TITLE
'PerpetualV2' object has no attribute 'perpetual_v2'

### ISSUE THREAD

**Issue by RobinDala2020** [niewiemczego/python-bingx#5]
Hello
I faced the error (AttributeError: 'PerpetualV2' object has no attribute 'perpetual_v2') when inputting the below command in Python 3.11:
`response = bingx_client.perpetual_v2.market.get_ticker("BTC-USDT")
![Bing](https://github.com/niewiemczego/python-bingx/assets/129304303/88aa37f6-a260-49e3-9010-6d74444f36fb)
`
please guide me.
BR,

**Comment by niewiemczego** [comment]
How does your `bingx_client` looks like?
Also please try to run it with 3.10 and check if you have the same issue.

From first sight it looks like you have used:
```python
from bingX.perpetual.v2 import PerpetualV2

bingx_client = PerpetualV2(api_key="api_key", secret_key="secret_key")
```
and if so then you should do this:
```python
bingx_client.market.get_ticker("BTC-USDT")
```
