### ISSUE TITLE
Can't open Short Position *help needed*

### ISSUE THREAD

**Issue by selfmadeKI** [niewiemczego/python-bingx#7]
# @niewiemczego 

-Hi, thank you for this project but I have a problem with position opening. (V2 Perpetual). Long Position is not a problem - is working but not Short position. When I try to open short postion I get:

Order details: Order(symbol='AXS-USDT', side=<Side.SELL: 'SELL'>, position_side=<PositionSide.SHORT: 'SHORT'>, quantity=1.0, type=<OrderType.MARKET: 'MARKET'>, price=None, stop_price=None, recv_window=None)
Client error: No position to close

I want to open a short position and not close any position. 

Can you help?

**Comment by niewiemczego** [comment]
Hey I have updated the codebase - now you will have to use positionSide instead of position_side

**Comment by selfmadeKI** [comment]
Hey thank you for you really fast reply and solving the problem. I really appreciate that. It helped and it seems to be working.
:))
